export const ROLES = [
    {
        value: 'super_admin',
        label: 'Super Admin',
        description: 'Global system setup and root level access',
        color: '#7f1d1d',
        permissions: ['*'],
    },
    {
        value: 'admin',
        label: 'Administrator',
        description: 'Full system management and configuration',
        color: '#dc2626',
        permissions: ['*'],
    },
    {
        value: 'warehouse_manager',
        label: 'Warehouse Manager',
        description: 'Full control over inventory, stock, and logistics',
        color: '#ea580c',
        permissions: [
            'dashboard.view',
            'products.view', 'products.create', 'products.edit',
            'categories.manage', 'brands.manage', 'uom.manage',
            'inventory.view', 'inventory.adjust', 'inventory.transfer', 'inventory.opening',
            'warehouses.manage',
            'purchasing.view', 'grn.manage',
            'suppliers.view',
            'damages.view', 'damages.manage',
            'repairs.view', 'repairs.manage',
            'supplier_returns.view', 'supplier_returns.manage',
            'reports.inventory',
        ],
    },
    {
        value: 'sales_manager',
        label: 'Sales Manager',
        description: 'Manages sales team, CRM, and accounts receivable',
        color: '#2563eb',
        permissions: [
            'dashboard.view',
            'products.view',
            'inventory.view',
            'sales.view', 'sales.create', 'sales.edit', 'sales.approve', 'sales.delete',
            'customers.view', 'customers.manage', 'customer_groups.manage',
            'pos.access',
            'invoices.view', 'invoices.create', 'invoices.edit',
            'payments.view', 'payments.manage',
            'credit_notes.view', 'credit_notes.manage',
            'returns.view', 'returns.manage',
            'reports.sales',
        ],
    },
    {
        value: 'hr_manager',
        label: 'HR Manager',
        description: 'Handles recruitment, payroll, and employee records',
        color: '#c026d3',
        permissions: [
            'dashboard.view',
            'hr.employees.view', 'hr.employees.manage',
            'hr.departments.manage', 'hr.designations.manage',
            'hr.shifts.manage',
            'hr.attendance.view', 'hr.attendance.manage',
            'hr.leaves.view', 'hr.leaves.manage',
            'hr.holidays.manage',
            'hr.salary.view', 'hr.salary.manage',
            'hr.payroll.view', 'hr.payroll.manage',
            'reports.hr',
        ],
    },
    {
        value: 'accountant',
        label: 'Accountant',
        description: 'Manages financial records, payables, and reports',
        color: '#059669',
        permissions: [
            'dashboard.view',
            'invoices.view', 'invoices.create', 'invoices.edit',
            'bills.view', 'bills.manage',
            'payments.view', 'payments.manage',
            'credit_notes.view', 'credit_notes.manage',
            'purchasing.view',
            'sales.view',
            'customers.view',
            'suppliers.view',
            'reports.sales', 'reports.financial',
        ],
    },
    {
        value: 'cashier',
        label: 'Cashier',
        description: 'Point of sale operations and customer payments',
        color: '#0891b2',
        permissions: [
            'dashboard.view',
            'products.view',
            'inventory.view',
            'sales.view', 'sales.create',
            'customers.view',
            'pos.access',
            'invoices.view', 'invoices.create',
            'payments.view', 'payments.manage',
        ],
    },
    {
        value: 'employee',
        label: 'Employee',
        description: 'Self-service portal access only',
        color: '#64748b',
        permissions: [
            'dashboard.view',
            'hr.attendance.view',
            'hr.leaves.view',
            'hr.payroll.view',
        ],
    },
    // Compatibility Roles
    { value: 'manager', label: 'Manager', permissions: ['*'], color: '#ea580c' },
    { value: 'sales_rep', label: 'Sales Rep', permissions: ['sales.create', 'sales.view', 'customers.view'], color: '#7c3aed' },
    { value: 'warehouse_staff', label: 'Warehouse Staff', permissions: ['inventory.view', 'grn.manage'], color: '#0891b2' },
    { value: 'production_staff', label: 'Production Staff', permissions: ['bom.view', 'production.view'], color: '#c026d3' },
    { value: 'staff', label: 'Staff', permissions: ['dashboard.view'], color: '#64748b' },
];

export const getRoleConfig = (roleValue) =>
    ROLES.find((r) => r.value === roleValue) || ROLES[ROLES.length - 1];