import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

/**
 * Export data to CSV
 * @param {Array} data - Array of objects
 * @param {string} fileName - File name with extension
 */
export const exportToCSV = (data, fileName = 'export.csv') => {
    if (!data.length) return;
    
    const headers = Object.keys(data[0]);
    const csvRows = [];
    
    // Add headers
    csvRows.push(headers.join(','));
    
    // Add data rows
    for (const row of data) {
        const values = headers.map(header => {
            const escaped = ('' + row[header]).replace(/"/g, '\\"');
            return `"${escaped}"`;
        });
        csvRows.push(values.join(','));
    }
    
    const csvContent = csvRows.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    
    if (link.download !== undefined) {
        const url = URL.createObjectURL(blob);
        link.setAttribute('href', url);
        link.setAttribute('download', fileName);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
};

/**
 * Export data to Excel
 */
export const exportToExcel = (data, fileName = 'export', sheetName = 'Data') => {
    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    XLSX.writeFile(workbook, `${fileName}.xlsx`);
};

/**
 * Export data to PDF with professional layout
 */
export const exportToPDF = async (title, columns, data, fileName = 'report', metadata = {}) => {
    const doc = new jsPDF({
        orientation: columns.length > 6 ? 'landscape' : 'portrait',
        unit: 'mm',
        format: 'a4'
    });
    
    const pageWidth = doc.internal.pageSize.width;

    // Load Company Logo
    const logoData = await new Promise((resolve) => {
        const img = new Image();
        img.crossOrigin = 'Anonymous';
        img.src = '/logo.jpg';
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0);
            resolve(canvas.toDataURL('image/jpeg'));
        };
        img.onerror = () => resolve(null);
    });
    
    // 1. Header Section
    // Draw Logo
    if (logoData) {
        doc.addImage(logoData, 'JPEG', 14, 10, 15, 15);
    }

    doc.setTextColor(33, 33, 33);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    // Company Name instead of WHOLESALE ERP
    doc.text('New Lanka Livestock And Animals Produce Farm', logoData ? 33 : 14, 16);
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text('Enterprise Resource Management System', logoData ? 33 : 14, 22);
    
    // 2. Report Info (Right-aligned)
    doc.setFontSize(10);
    doc.setTextColor(33, 33, 33);
    doc.setFont('helvetica', 'bold');
    doc.text(title.toUpperCase(), pageWidth - 14, 16, { align: 'right' });
    
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    
    let yPosRight = 20;
    doc.text(`Report Date: ${new Date().toLocaleString()}`, pageWidth - 14, yPosRight, { align: 'right' });
    if (metadata.userName) {
        yPosRight += 4;
        doc.text(`Generated by: ${metadata.userName} (${metadata.userRole || 'User'})`, pageWidth - 14, yPosRight, { align: 'right' });
    }

    // Line separator
    const lineY = logoData ? 28 : Math.max(25, yPosRight + 3);
    doc.setDrawColor(220, 220, 220);
    doc.line(14, lineY, pageWidth - 14, lineY);

    // 3. Table Section
    autoTable(doc, {
        startY: lineY + 4,
        head: [columns.map(col => col.header)],
        body: data.map(item => columns.map(col => {
            const val = item[col.dataKey];
            if (val === null || val === undefined) return '—';
            if (typeof val === 'number') return val.toLocaleString('en-LK', { minimumFractionDigits: 2 });
            if (typeof val === 'object') return val.name || val.code || JSON.stringify(val);
            return String(val);
        })),
        theme: 'striped',
        headStyles: { 
            fillColor: [30, 41, 59], // slate-800
            textColor: [255, 255, 255],
            fontSize: 9,
            fontStyle: 'bold',
            halign: 'center'
        },
        styles: { 
            fontSize: 8,
            cellPadding: 3,
            valign: 'middle'
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252] // slate-50
        },
        margin: { left: 14, right: 14 },
        didDrawPage: (data) => {
            // Footer
            const str = `Page ${doc.internal.getNumberOfPages()}`;
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(str, pageWidth - 14, doc.internal.pageSize.height - 10, { align: 'right' });
            doc.text('Confidential - System Generated Report', 14, doc.internal.pageSize.height - 10);
        }
    });
    
    doc.save(`${fileName}.pdf`);
};
